CREATE USER 'USER'@'localhost' IDENTIFIED BY 'PASSWORD';
CREATE USER 'USER'@'%' IDENTIFIED BY 'PASSWORD';

GRANT SELECT, INSERT, UPDATE, DELETE ON Biblioteca.* TO 'USER'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON Biblioteca.* TO 'USER'@'%';
